#!/usr/bin/env node
/**
 * Generates Zod schemas from the OpenAPI document.
 *
 * `openapi-typescript` gives us compile-time types; those vanish at runtime, so anything crossing
 * the network still needs a runtime check. Both come from the same document, generated in the same
 * command, so a client type and a client validator cannot disagree with each other or with the
 * contract — which is the drift invariant #11 exists to prevent.
 *
 * The subset handled here is the subset the contract uses. When API-01 introduces a shape this does
 * not cover, the generator fails loudly on it rather than emitting `z.unknown()` and letting an
 * unvalidated field through as if it had been checked.
 *
 * The translation functions are exported and unit-tested; the file I/O runs only when this module is
 * executed directly.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { parse } from 'yaml'

const REF_PREFIX = '#/components/schemas/'

/** @param {string} ref */
export function refName(ref) {
  if (!ref.startsWith(REF_PREFIX)) {
    throw new Error(`Only local component references are supported, got: ${ref}`)
  }
  return `${ref.slice(REF_PREFIX.length)}Schema`
}

/**
 * @param {Record<string, any>} schema
 * @param {string} path for the error message, so a failure names the field rather than the file
 * @returns {string} a Zod expression
 */
export function toZod(schema, path) {
  if (typeof schema.$ref === 'string') return refName(schema.$ref)

  switch (schema.type) {
    case 'object': {
      const properties = schema.properties ?? {}
      const required = new Set(schema.required ?? [])
      const fields = Object.entries(properties).map(([key, value]) => {
        const expression = toZod(value, `${path}.${key}`)
        return `  ${key}: ${required.has(key) ? expression : `${expression}.optional()`},`
      })
      return `z.object({\n${fields.join('\n')}\n})`
    }
    case 'string':
      return Array.isArray(schema.enum)
        ? `z.enum([${schema.enum.map((value) => JSON.stringify(value)).join(', ')}])`
        : 'z.string()'
    case 'integer':
      return 'z.number().int()'
    case 'number':
      return 'z.number()'
    case 'boolean':
      return 'z.boolean()'
    case 'array':
      return `z.array(${toZod(schema.items ?? {}, `${path}[]`)})`
    default:
      throw new Error(
        `${path}: unsupported schema type ${JSON.stringify(schema.type)}. Extend ` +
          'scripts/generate-zod.mjs rather than letting an unvalidated shape through.',
      )
  }
}

/** Emit a schema only after everything it references, since `const` is not hoisted. */
export function inDependencyOrder(schemas) {
  const remaining = new Map(Object.entries(schemas))
  const emitted = new Set()
  const ordered = []

  while (remaining.size > 0) {
    const ready = [...remaining].filter(([, schema]) =>
      [...JSON.stringify(schema).matchAll(/"\$ref":"([^"]+)"/g)]
        .map(([, ref]) => ref.slice(REF_PREFIX.length))
        .every((dependency) => emitted.has(dependency)),
    )
    if (ready.length === 0) {
      throw new Error(`Cyclic $ref among: ${[...remaining.keys()].join(', ')}`)
    }
    for (const [name, schema] of ready) {
      ordered.push([name, schema])
      emitted.add(name)
      remaining.delete(name)
    }
  }
  return ordered
}

/** @param {Record<string, any>} document a parsed OpenAPI document */
export function render(document) {
  const schemas = document.components?.schemas ?? {}
  const body = inDependencyOrder(schemas)
    .map(([name, schema]) => `export const ${name}Schema = ${toZod(schema, name)}\n`)
    .join('\n')

  return `/* eslint-disable */
// Generated by scripts/generate-zod.mjs from backend/api-rest/src/main/resources/openapi.yaml.
// Do not edit by hand: CI regenerates this file and fails on a diff.

import { z } from 'zod'

${body}`
}

function main() {
  const here = dirname(fileURLToPath(import.meta.url))
  const contract = resolve(here, '../../backend/api-rest/src/main/resources/openapi.yaml')
  const target = resolve(here, '../src/api/generated/schemas.ts')

  const document = parse(readFileSync(contract, 'utf8'))
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, render(document), 'utf8')
  console.log(
    `Wrote ${Object.keys(document.components?.schemas ?? {}).length} schema(s) to ` +
      'src/api/generated/schemas.ts',
  )
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
