#!/usr/bin/env python3
"""generate_docs_map.py — regenerate docs/docs_map.md, the heading inventory.

A generator/check pair: `--check` fails when the map drifted from the headings, so the
inventory can never go stale silently. The map itself is excluded from its own input set,
otherwise writing it would change the input and `--check` could never be stable.

Usage:
    python scripts/generate_docs_map.py            # write
    python scripts/generate_docs_map.py --check    # fail if stale (CI)

stdlib-only, Windows-safe.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _common import (  # noqa: E402
    MAP_DIRS, extract_headings, fm_str, force_utf8, ignored_paths, is_ignored,
    parse_frontmatter, repo_root,
)

HEADER = """<!-- GENERATED by scripts/generate_docs_map.py — do not edit by hand. -->

# Documentation map

Every heading in `docs/` and `skills/`, so a contributor (or a tool) can find the right
section without opening ten files. Regenerate with `python scripts/generate_docs_map.py`.
"""


def iter_map_files(root: Path) -> list[Path]:
    generated = (root / "docs" / "docs_map.md").resolve()
    ignored = ignored_paths(root)
    files: list[Path] = []
    for d in MAP_DIRS:
        files += (root / d).rglob("*.md")
    files = [
        f for f in files
        if f.resolve() != generated
        and not is_ignored(f.resolve().relative_to(root).as_posix(), ignored)
    ]
    return sorted(files, key=lambda p: p.resolve().relative_to(root).as_posix())


def render(root: Path) -> str:
    lines = [HEADER]
    for path in iter_map_files(root):
        rel = path.resolve().relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        summary = fm_str(parse_frontmatter(text), "summary")
        lines.append(f"\n## `{rel}`\n")
        if summary:
            lines.append(f"> {summary}\n")
        for level, title in extract_headings(text):
            lines.append(f"{'  ' * (level - 1)}- {title}")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the documentation heading map.")
    parser.add_argument("--check", action="store_true", help="fail if the map is stale")
    args = parser.parse_args(argv)

    force_utf8()
    root = repo_root()
    target = root / "docs" / "docs_map.md"
    rendered = render(root)

    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != rendered:
            print("FAIL - docs/docs_map.md is stale.", file=sys.stderr)
            print("       run: python scripts/generate_docs_map.py", file=sys.stderr)
            return 1
        print("OK - docs/docs_map.md is current.")
        return 0

    target.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {target.relative_to(root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
